version: "3"
services:
  zinlo_api:
    container_name: zinlo_api
    build:
      context: aspnet-core
      dockerfile: migrator.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ${CONNECTION_STRING}
    volumes:
      - ./data-dir/App_Data/Logs:/app/App_Data/Logs
