version: "3"
services:
  zinlo_api:
    container_name: zinlo_api
    build:
      context: aspnet-core
      dockerfile: api.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ${CONNECTION_STRING}
      "App:ServerRootAddress": ${SEVER_ROOT_ADDRESS}
      "App:CorsOrigins": ${CORS_ORIGIN}
      "App:DomainFormat": ${DOMAIN_FORMAT}
      "AbpZeroLicenseCode": ${AbpZeroLicenseCode}
      "Authentication:JwtBearer:IsEnabled": "true"
      "Authentication:JwtBearer:SecurityKey": ${JWT_SECURITY_KEY}
      "Authentication:JwtBearer:Issuer": ${JWT_ISSUER}
      "Authentication:JwtBearer:Audience": ${JWT_AUDIENCE}
      "Stripe:IsActive": "true"
      "Stripe:BaseUrl": "https://api.stripe.com/v1"
      "Stripe:SecretKey": ${STRIPE_SECRET_KEY}
      "Stripe:PublishableKey": ${STRIPE_PUBLISH_KEY}
      "Stripe:WebhookSecret": ""
      "Stripe:PaymentMethodTypes": ["card"]
    ports:
      - "8080:80"
    volumes:
      - ./data-dir/App_Data/Logs:/app/App_Data/Logs
      - ./data-dir/Uploads-Attachments:/app/wwwroot/Uploads-Attachments
  zinlo_web:
    container_name: zinlo_web
    build:
      context: angular
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/appsettings.production.json:/usr/share/nginx/html/appsettings.production.json
    depends_on:
      - zinlo_api
    links:
      - zinlo_api:zinlo_api
    ports:
      - "80:80"
