version: "3"
services:
  zinlo_api:
    container_name: zinlo_api
    build:
      context: aspnet-core
      dockerfile: aspnet-core.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ${CONNECTION_STRING}
      "App:ServerRootAddress": ${SEVER_ROOT_ADDRESS}
      "App:CorsOrigins": ${CORS_ORIGIN}
      "App:DomainFormat": ${DOMAIN_FORMAT}
      "Authentication:JwtBearer:IsEnabled": "true"
      "Authentication:JwtBearer:SecurityKey": ${JWT_SECURITY_KEY}
      "Authentication:JwtBearer:Issuer": ${JWT_ISSUER}
      "Authentication:JwtBearer:Audience": ${JWT_AUDIENCE}
    ports:
      - "8081:80"
    volumes:
      - ./data-dir/App_Data/Logs:/app/App_Data/Logs
      - ./data-dir/Uploads-Attachments:/app/wwwroot/Uploads-Attachments
  zinlo_web:
    container_name: zinlo_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_API_URL: ${APP_API_URL}
    ports:
      - "80:80"
