# This is a basic workflow to help you get started with Actions

name: Zinlo Angular

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      working-directory: ./angular
      run: npm install
    - name: Build
      working-directory: ./angular
      run: npm run build -- --prod
    
