# This is a basic workflow to help you get started with Actions

name: ZinloAngular
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
jobs:
 build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      working-directory: ./angular
      run: npm install
    - name: Build
      working-directory: ./angular
      run: ng build --aot --prod 
    
