name: Zinlo

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      working-directory : ./aspnet-core/src/Zinlo.Web.Host
      run: dotnet restore
    - name: Build Zinlo
      run: dotnet build --configuration Release --no-restore
      working-directory: ./aspnet-core/src/Zinlo.Web.Host
  
