name: Zinlo

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v1
      
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ./aspnet-core/src/Zinlo.Web.Host
      run: dotnet restore ./aspnet-core/Zinlo.Web.sln --configuration Release
    - name: Build Zinlo
      run: dotnet build ./aspnet-core/Zinlo.Web.sln --configuration Release --no-restore
      
  
